### ISSUE TITLE
Is it possible to package the payload with electron-packager?

### ISSUE THREAD

**Issue by OmarCuadradoFree** [roccomuso/netrat#5]
@roccomuso 
Since the packaging wasnt working with UPx X i look for an alternative option of packaging the app AND i found electro-packager, and I was wondering if is possible to do this with electron, I already tryit but it doesnt work =( thanks

**Comment by OmarCuadradoFree** [comment]
![image](https://user-images.githubusercontent.com/18033928/36942831-b1bd5e02-1f4a-11e8-89a7-d6cc97eff9c0.png)

question, Once I created the payload where this file will be , I mean at the current project I cant just see this
![image](https://user-images.githubusercontent.com/18033928/36942836-d962d950-1f4a-11e8-932b-d84727e273aa.png)

the red ones belongs to electron, so where is the file that netrat creates?

Ty by the way Im quit new but I love learning :D 
👍

**Comment by OmarCuadradoFree** [comment]
Got Idea we can packegin just the final output I mean just the "payload.js" and add that code to the html , and that could works, question,,, where is that "payload.js" xD

**Comment by roccomuso** [comment]
What do you mean by "add that code to the html"? the netrat seed works only server-side. There's no browser-side code involved.
Moreover I don't see the point of using `electron-packager`. UPX is required to compress the output bin file. It would be required also with electron if you wanna reduce the size.

Otherwise just use the normale `netrat` and the embedded `pkg` to build your binary file and avoid the compression with upx.

**Comment by OmarCuadradoFree** [comment]
@roccomuso hi there once again, ammmm Im quite new using all of these and I have a doubt, once the I got the 
![image](https://user-images.githubusercontent.com/18033928/36958410-99157e6a-2009-11e8-97fb-0c8502ffc31b.png) 

where is located the output file, I mean this is requiered if I wannt to use pkg to package the output bin, ty for your help I know this could be annoying but Im still learning ty.

**Comment by OmarCuadradoFree** [comment]
This Is what Iam doing,
1) I download this repository as rar file and I  decompresses it.
2) I make "npm install"
3) then, I install pkg
4) I run the command netrat And i put everything , (I say no to the packagin with UPX) 
5) I open up the directory where Everything is and i typed "npm pkg ."
6) Is it that ok? or there is something I missen out. 

TY

**Comment by roccomuso** [comment]
Just do: `npm i -g netrat`
And then from your terminal run `netrat`.
Then follow the wizard and you should get a compiled binary file into the current directory.
That's it.

**Comment by OmarCuadradoFree** [comment]
@roccomuso Yeah bru you ware right it was as simple as that, :D 
I was just trying to undertsand well how everything works,,
I have Another doubt, you said that this could be up gradable to meterpreter so, how to make it.
I mean I can establish the connection using multi/handler and set the value of the payload as windows/x64/shell which gives to me a DOS shell but Is it possible to use meterpreter as back end shell?
if so , how can I make it
 Thanks and chees. 👍

**Comment by roccomuso** [comment]
Watch some tutorial on how to upgrade to meterpreter the shell.

**Comment by OmarCuadradoFree** [comment]
@roccomuso hi there, bro is it posibble to add the https://www.npmjs.com/package/auto-launch 
npm to the netrat.exe , to start up at the boot ?

**Comment by roccomuso** [comment]
@OmarCuadrado yeah but let's close this issue and open another one. That's a different topic.

**Comment by OmarCuadradoFree** [comment]
What Im triying to do is this.

1) first I install the auto-launch module  (npm install --save auto-launch) 
2) Then I check out the .json file and check the dependencies 

![image](https://user-images.githubusercontent.com/18033928/37103489-5ef02028-21f8-11e8-9746-6401dad950c1.png)

3) Then I add this code to the cli.js (since is the main js function)

![image](https://user-images.githubusercontent.com/18033928/37103590-92c96256-21f8-11e8-819a-b157134e3395.png)

4) Then I make npm install and pkg .
5) then I execute the pkg windows version, And i got this error 

![image](https://user-images.githubusercontent.com/18033928/37103706-d6495fe0-21f8-11e8-8ad7-5a0696a80fa1.png)

Is this the way that should be implemented?
Ty
#5
