### ISSUE TITLE
Auto-lunch on the netrat.exe 

### ISSUE THREAD

**Issue by OmarCuadradoFree** [roccomuso/netrat#6]
@roccomuso 

issue #5

**Comment by OmarCuadradoFree** [comment]
What Im triying to do is this.

    first I install the auto-launch module (npm install --save auto-launch)
    Then I check out the .json file and check the dependencies

![image](https://user-images.githubusercontent.com/18033928/37103864-41769b20-21f9-11e8-8f8f-d7c7d0224b1d.png)


    Then I add this code to the cli.js (since is the main js function)

![image](https://user-images.githubusercontent.com/18033928/37103886-4e5f4742-21f9-11e8-8845-88ef96be03e3.png)


    Then I make npm install and pkg .
    then I execute the pkg windows version, And i got this error

![image](https://user-images.githubusercontent.com/18033928/37103907-5bab8820-21f9-11e8-891b-2dfe17ed7539.png)


Is this the way that should be implemented?
Ty

**Comment by roccomuso** [comment]
1. You're putting code in a wrong location.

2. You're trying to use `Electron`'s methods when this is clearly not an electron project.

The best way to use `auto-launch` with `netrat` is to having your payload-shell copying itself in a safe/hidden place and then use this script to set the autorun:

```javascript
const AutoLaunch = require('auto-launch')

let shellAutoLauncher = new AutoLaunch({
	name: 'netrat-shell',
	path: '/srv/netrat-shell', // <-- safe/hidden place
})
shellAutoLauncher.isEnabled()
.then(function(isEnabled){
	if(isEnabled){
	    return;
	}
	shellAutoLauncher.enable()
}).catch(function(err){
    // handle error
})
```

**Comment by OmarCuadradoFree** [comment]
@roccomuso 
Hi bro, I check out what you said about the autolunch ,this is what i did but doesnt work,

1) I modifie the auto-launch file like this

![image](https://user-images.githubusercontent.com/18033928/37134531-fb35a250-2266-11e8-9512-4b5991279a82.png)

2) in order to make executable I use electron packager (I dont know if this could be the problem , i dont know how to pack with another packager ;p ) since I just need to call this ,js something like index.js this what exactly i did. when I execute this is what appears at the start up of windows.

![image](https://user-images.githubusercontent.com/18033928/37134638-6acaf958-2267-11e8-9863-90ecba81116e.png)

the blue one is using the .js exactly like you wrote it, whats over after restart nothing happen, is there something that Im missing out,

Ty bro for your patient I really apologies
ty
👍

**Comment by OmarCuadradoFree** [comment]
IM triying to make it for windows, in this case what could be the PATH options, If I store the netrat.exe inside of downloads for instence.

👍

**Comment by roccomuso** [comment]
You have to copy the binary to a valid windows path. Feel free to choose it.
