### ISSUE TITLE
every single build fails on macOS no matter what the settings are

### ISSUE THREAD

**Issue by therealtear** [roccomuso/netrat#8]
![Screen Shot 2021-03-15 at 5 36 29 PM](https://user-images.githubusercontent.com/63162279/111234797-fb339000-85b4-11eb-899a-166d6d51cb98.png)
normally there isnt even an error message it just says build failed this is the longest error message I've gotten so far which seems that the packager is just out of date and doesnt have the right names of the releases on github but most times there is nothing showing other then build failed

**Comment by roccomuso** [comment]
Since this module has no package-lock.json, maybe a dependency upgrade broke something.
Could you try downgrading some deps?

Once we find the working versions we can lock them.

I cannot test myself since I don't have a Mac to play with at the moment.

**Comment by therealtear** [comment]
> Since this module has no package-lock.json, maybe a dependency upgrade broke something.
> Could you try downgrading some deps?
> 
> Once we find the working versions we can lock them.
> 
> I cannot test myself since I don't have a Mac to play with at the moment.

sure thing ill do that later tonight also i think one of the problems is just the links being out of date and not having the right release version like i mentioned

**Comment by therealtear** [comment]
ok so turns out building with pkg is a big problem that i dont have time to fix rn for mac but out of curiosity how would I set up the command sending server to actually send commands to the listener payload?

**Comment by therealtear** [comment]
ive been doing a lot more testing and updating all the packages did actually get it to work however the options are very limited I was only able to build a non compressed payload with node v8 on x64 (obviously) but I think the issue might be with UPX because although I can build payloads only with node v8 and nothing else it still fails when I enable the UPX compression flag and I even tried adjusting the actual command with the newer version of UPX and it still doesnt seem to be working I can push my updated package.json and package-lock if you want
